export default class PatientCancer {
  constructor() {
    // this.rec_code = null
    this.entrance = null
    this.patient_id = null
    this.patient_code = null
    this.finance_support_code = null
    this.recurrent = null
    this.recurrent_date = null
    this.finance_support_code = null
    this.finance_support_text = null
    this.diagnosis_code = null
    this.diagnosis_text = null
    this.diagnosis_out = null
    this.icd10_code = null
    this.icd10_text = null
    this.topo_id = null
    this.topo_code = null
    this.topo_text = null
    this.morphology_code = null
    this.morphology_text = null
    this.behaviour_code = null
    this.behaviour_text = null
    this.grade_code = null
    this.grade_text = null
    this.stage_code = null
    this.t_code = null
    this.n_code = null
    this.m_code = null
    this.tnm_date = null
    this.biopsy_sent_date = null
    this.extension_code = null
    this.metastasis = []
    this.metastasis_organ = null
    this.lifestatus_code = null
    this.last_seen = null
    // this.death_date = null
    // this.deathcause_code = null
    this.txt_clinical_sammary = null
    this.txt_patho = null
    this.txt_lab = null
    this.txt_xray = null
    this.create_by = null
    this.create_date = null
    this.last_update_by = null
    this.last_update_date = null
    this.clinical_summary = null

    this.diagnosis_date = null
    this.age = null
    this.excision_in_num = null
    this.excision_in_cut_date = null
    this.excision_in_read_date = null
    // this.excision_out_num = null
    // this.excision_out_cut_date = null
    // this.excision_out_read_date = null
    this.recurent_code = null
    this.laterality_code = null
    this.contact_last_date = null

    // this.refer_from_hos_code = null
    // this.refer_from_date = null
    // this.refer_from_hn = null
    // this.refer_from_detail = null
    // this.refer_to_hos_code = null
    // this.refer_to_date = null
    // this.refer_to_hn = null
    // this.refer_to_detail = null
  }
}
